import Head from "next/head";
import { useEffect, useState } from 'react';
import ContactForm from "/components/contactForm"
import ContactInfo from "/components/contactInfo";
import Image from 'next/image';

export default function Contact() {
    return(
        <>
    <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="">
    <section className=''>
          <div className='bannerbox'>
            <div className='container_cms flex-center'>
              <div className='banner-heading'>
                Contact MuslimHive
              </div>
            </div>
          </div>
        </section>
    <section className="flex gap-20 p-60">
        <div className="width-50"><ContactForm /></div>
        <div className="width-50 container">
        <Image className="rightImg" src="http://localhost:1337/uploads/undraw_contact_us_re_4qqt_98e07abd55.svg" width={100} height={100} objectFit="cover" />
        </div>
    </section>
      <ContactInfo />
    </main>
    </>
    );
}