import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Button, IconButton } from "/components/button"
import React, {lazy, Suspense, useState } from "react";
import ModalBox from "/components/ModalBoxWide";
import RegisterFrom from "/public/forms/register";
import Getlisted from "/public/forms/getlisted";
const CategoreyIconBox = lazy(() => import('/components/categoreyIconBox'));
import FindByLocation from "/components/findByLocation";
import StaticsCounter from "/components/statics";
// import WideSlider from "../../components/wideSlider";
import ContainerImage from "/public/container.png";
import SearchImage from "/public/Search.svg";
import Image1 from "/public/img1.svg";
import Image2 from "/public/img2.svg";
import Image3 from "/public/img3.svg";
import Image4 from "/public/img4.svg";
import Image5 from "/public/img5.svg";
import profile from "/public/assets/images/profile.png";
import carousel from "/public/assets/images/Carousel.svg";
import supermarket from "/public/assets/images/Supermarket.svg";
// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { categoreyList, categoreyList2 } from "../../components/menuOptions";
import Carousel from '/components/loopCarousel';
import GoToTop from '/components/gotoTop';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MuslimHives</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>
          
        </div>
        <div className="flex pad-ver-60 gap-80 space-between">
          <div className="container col gap-24 width-50">
            <FindByLocation />
            
          </div>
          <div className="width-50">
            <Image className="full-img" src={ContainerImage} width={"100%"} height={"100%"}/>
          </div>
        </div>

        <div className="flex gap-20">
          <Image src={Image1} className="width-60" />
          <Image src={Image2} className="width-15" />
          <Image src={Image3} className="width-15" />
          <Image src={Image4} className="width-15" />
          <Image src={Image5} className="width-15" />
        </div>

        <Suspense fallback={<div>Loading...</div>}>
        <CategoreyIconBox />
        </Suspense>
        
        <div className="container col gap-40 mt-100">
          <div className="container col gap-20">
            <h2>Popular Categories</h2>
            <div className="center">
              <p>Explore businesses across various categories</p>
            </div>
          </div>
          <div className="container gap-40">
            <div className="container width-60">
              <Image src={Image1} className="imgwidth" />
            </div>
            <div className="container width-20">
              <Image src={Image1} className="imgwidth" />
            </div>
            <div className="container width-20">
              <Image src={Image1} className="imgwidth" />
            </div>
          </div>
          <div className="container gap-40">
            <div className="container width-20">
              <Image src={Image1} className="imgwidth" />
            </div>
            <div className="container width-20">
              <Image src={Image1} className="imgwidth" />
            </div>
            <div className="container width-60">
              <Image src={Image1} className="imgwidth" />
            </div>
          </div>
        </div>
        <div className="p-60 container vCenter mt-100">
          <div className="width-60">
            <div>
              <h2 className="left">Why Choose Us?</h2>
              <p>Discover the benefits of using our platform</p>
            </div>
          </div>
          <div className="width-40 container gap-40 col">
            <div className="container vcards">
              <div>
                <Image src={Image1} className="imgwidth" />
              </div>
              <div>
                <div>
                  <h3>Verified Listings</h3>
                </div>
                <p>
                  All businesses listed on our platform are verified for
                  authenticity and quality
                </p>
              </div>
            </div>
            <div className="container vcards">
              <div>
                <Image src={Image1} className="imgwidth" />
              </div>
              <div>
                <div>
                  <h3>User Reviews</h3>
                </div>
                <p>
                  Read honest reviews from customers to make informed decisions
                </p>
              </div>
            </div>
            <div className="container vcards">
              <div>
                <Image src={Image1} className="imgwidth" />
              </div>
              <div>
                <div>
                  <h3>Easy Search</h3>
                </div>
                <p>
                  Effortlessly find businesses using our powerful search filters
                </p>
              </div>
            </div>
          </div>
          <div></div>
        </div>

        <div className="container p-10 vCenter  mt-100">
          <div className="width-60">
            <h2 className="left">Customer Reviews</h2>
          </div>
          <div className="width-40 flex gap-20">
            <div className="crCards width-50 flex col gap-10">
              <div className="imgBox flex space-between">
                <div className="flex gap-20 ">
                  <Image src={profile} />
                  <h3>John Doe</h3>
                </div>
                icons
              </div>
              <p>Great service and highly recommended!</p>
            </div>
            <div className="crCards width-50 flex col gap-10">
              <div className="imgBox flex space-between">
                <div className="flex gap-20 ">
                  <Image src={profile} />
                  <h3>John Doe</h3>
                </div>
                icons
              </div>
              <p>Great service and highly recommended!</p>
            </div>
          </div>
        </div>
        <div className="p-60 fBusiness flex col gap-20  mt-100">
          <h2>Featured Businesses</h2>.
          <div className="oN fBCarousel">
          <Carousel slidesPerView={5}/>
          </div>
          <div className="flex space-around p-60">
            <div className="rating-IconBox">
              <div>
                <Image src={supermarket} />
                <h3>ABC Supermarket</h3>
                <span>Grocery Store</span>
              </div>
              <div>4.5 stars</div>
            </div>
            <div className="rating-IconBox">
              <div>
                <Image src={supermarket} />
                <h3>ABC Supermarket</h3>
                <span>Grocery Store</span>
              </div>
              <div>4.5 stars</div>
            </div>
            <div className="rating-IconBox">
              <div>
                <Image src={supermarket} />
                <h3>ABC Supermarket</h3>
                <span>Grocery Store</span>
              </div>
              <div>4.5 stars</div>
            </div>
          </div>
        </div>
        <div>
          <Getlisted />
        </div>
        <div className="">
          <div>
          <h2>
          Business Statistics
          </h2>
          <p className="center">
          Insights and analytics to track your business performance
          </p>
          </div>
          <div className="flex space-between p-60 gap-80">
            <StaticsCounter />
          </div>
        </div>
      </main>
      <GoToTop />
    </>
  );
}
